import {
  GlobalSpace1,
  GlobalSpace10,
  GlobalSpace11,
  GlobalSpace12,
  GlobalSpace13,
  GlobalSpace14,
  GlobalSpace15,
  GlobalSpace16,
  GlobalSpace2,
  GlobalSpace3,
  GlobalSpace4,
  GlobalSpace5,
  GlobalSpace6,
  GlobalSpace7,
  GlobalSpace8,
  GlobalSpace9,
} from '../../../theme/js/global'

export const space = {
  space1: GlobalSpace1,
  space2: GlobalSpace2,
  space3: GlobalSpace3,
  space4: GlobalSpace4,
  space5: GlobalSpace5,
  space6: GlobalSpace6,
  space7: GlobalSpace7,
  space8: GlobalSpace8,
  space9: GlobalSpace9,
  space10: GlobalSpace10,
  space11: GlobalSpace11,
  space12: GlobalSpace12,
  space13: GlobalSpace13,
  space14: GlobalSpace14,
  space15: GlobalSpace15,
  space16: GlobalSpace16,
}
