export const Global140 : string;
export const Global150 : string;
export const Global160 : string;
export const GlobalBaseSpace : number;
export const GlobalSpace1 : number;
export const GlobalSpace2 : number;
export const GlobalSpace3 : number;
export const GlobalSpace4 : number;
export const GlobalSpace5 : number;
export const GlobalSpace6 : number;
export const GlobalSpace7 : number;
export const GlobalSpace8 : number;
export const GlobalSpace9 : number;
export const GlobalSpace10 : number;
export const GlobalSpace11 : number;
export const GlobalSpace12 : number;
export const GlobalSpace13 : number;
export const GlobalSpace14 : number;
export const GlobalSpace15 : number;
export const GlobalSpace16 : number;
export const GlobalBlack : string;
export const GlobalWhite : string;
export const GlobalGray100 : string;
export const GlobalGray200 : string;
export const GlobalGray300 : string;
export const GlobalGray400 : string;
export const GlobalGray500 : string;
export const GlobalGray600 : string;
export const GlobalGray700 : string;
export const GlobalGray800 : string;
export const GlobalGray900 : string;
export const GlobalRed100 : string;
export const GlobalRed200 : string;
export const GlobalRed300 : string;
export const GlobalRed400 : string;
export const GlobalRed500 : string;
export const GlobalRed600 : string;
export const GlobalRed700 : string;
export const GlobalRed800 : string;
export const GlobalRed900 : string;
export const GlobalYellow100 : string;
export const GlobalYellow200 : string;
export const GlobalYellow300 : string;
export const GlobalYellow400 : string;
export const GlobalYellow500 : string;
export const GlobalYellow600 : string;
export const GlobalYellow700 : string;
export const GlobalYellow800 : string;
export const GlobalYellow900 : string;
export const GlobalBlue100 : string;
export const GlobalBlue200 : string;
export const GlobalBlue300 : string;
export const GlobalBlue400 : string;
export const GlobalBlue500 : string;
export const GlobalBlue600 : string;
export const GlobalBlue700 : string;
export const GlobalBlue800 : string;
export const GlobalBlue900 : string;
export const GlobalGreen100 : string;
export const GlobalGreen200 : string;
export const GlobalGreen300 : string;
export const GlobalGreen400 : string;
export const GlobalGreen500 : string;
export const GlobalGreen600 : string;
export const GlobalGreen700 : string;
export const GlobalGreen800 : string;
export const GlobalGreen900 : string;
export const GlobalInfoAccent : string;
export const GlobalInfoNegative : string;
export const GlobalInfoWarning : string;
export const GlobalInfoPositive : string;
export const GlobalInfoPositiveTransparent : string;
export const GlobalInfoNegativeTransparent : string;
export const GlobalPretendard : string;
export const GlobalRegular : number;
export const GlobalSemiBold : number;
export const GlobalBold : number;
export const GlobalFontScale : number;
export const GlobalDefault : number;
export const GlobalSmall : number;
export const GlobalMedium : number;
export const GlobalLarge : number;
export const GlobalXL : number;
export const GlobalXXL : number;
export const GlobalXXXL : number;
export const GlobalHeadingMedium : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalHeadingLarge : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalHeadingXL : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalHeadingXXL : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalHeadingXXXL : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalLabelSmall : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalLabelMedium : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalLabelLarge : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalLabelXL : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalLabelXXL : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalParagraphSmall : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalParagraphMedium : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalParagraphLarge : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalParagraphXL : { fontFamily: string, fontWeight: number, lineHeight: string, fontSize: number, letterSpacing: string, paragraphSpacing: string, textDecoration: string, textCase: string };
export const GlobalButton : number;
export const GlobalAboveHigh : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const GlobalAboveMedium : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const GlobalAboveLow : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const GlobalBelowHigh : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const GlobalBelowMedium : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const GlobalBelowLow : { color: string, type: string, x: number, y: number, blur: number, spread: number };
export const GlobalPink100 : string;
export const GlobalPink200 : string;
export const GlobalPink300 : string;
export const GlobalPink400 : string;
export const GlobalPink500 : string;
export const GlobalPink600 : string;
export const GlobalPink700 : string;
export const GlobalPink800 : string;
export const GlobalPink900 : string;
export const GlobalOragneOrange : string;
export const LightPrimary : string;
export const LightSecondary : string;
export const LightTertiary : string;
export const LightContentsContentPrimary : string;
export const LightContentsContentSecondary : string;
export const LightContentsContentTertiary : string;
export const LightBorderBorderOpaque : string;
export const LightBorderBorderTransparent : string;
export const DarkPrimary : string;
export const DarkSecondary : string;
export const DarkTertiary : string;
export const DarkContentsContentPrimary : string;
export const DarkContentsContentSecondary : string;
export const DarkContentsContentTertiary : string;
export const DarkBorderBorderOpaque : string;
export const DarkBorderBorderTransparent : string;
export const $metadataTokenSetOrder0 : string;
export const $metadataTokenSetOrder1 : string;
export const $metadataTokenSetOrder2 : string;